## 1  Lists operation

In [21]:
lst = [10,20,30,40,50,]
print(lst)

[10, 20, 30, 40, 50]


In [22]:
lst.append(60)
lst

[10, 20, 30, 40, 50, 60]

In [23]:
lst.extend([70,80,90])
lst

[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [24]:
lst.insert(2,25)   # inserts the elemnet at that index
lst

[10, 20, 25, 30, 40, 50, 60, 70, 80, 90]

In [25]:
lst.remove(25)    # removes the elemnt in the list
lst

[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [26]:
lst.pop(2)     # removes element at the index
lst

[10, 20, 40, 50, 60, 70, 80, 90]

In [30]:
lst[2:5]

[40, 50, 60]

In [31]:
lst.count(20)

1

In [36]:
lst.sort()
lst

[10, 20, 40, 50, 60, 70, 80, 90]

In [37]:
lst.reverse()
lst

[90, 80, 70, 60, 50, 40, 20, 10]

## 2  Tuples

In [38]:
tp=('ravi','shankr','manoj')
tp

['ravi', 'shankr', 'manoj']

In [39]:
tp[1]=rakshita  ## tuplea are immutable so when i try to update it gives me error
tp

NameError: name 'rakshita' is not defined

## 3 Sets

In [40]:
myset={1,2,3,5,5,7,8,9,}
myset

{1, 2, 3, 5, 7, 8, 9}

In [41]:
thisset = {"apple", "banana", "cherry", "apple"}
print(thisset)  ## sets cannot have the duplicates value so when we print it we get only distinct

{'banana', 'apple', 'cherry'}


## 4 Dictionary

In [42]:
student={"name":"ravi","age":"23","city":"Belagavi"}
print(student)

{'name': 'ravi', 'age': '23', 'city': 'Belagavi'}


In [43]:
student["age"]=22 ## updating the age from 23 to 22
print(student)

{'name': 'ravi', 'age': 22, 'city': 'Belagavi'}


In [44]:
student["email"]="ravi@gmmail.com"
print(student)

{'name': 'ravi', 'age': 22, 'city': 'Belagavi', 'email': 'ravi@gmmail.com'}


## 5 voting

In [47]:
age=int(input('Enter the age'))

if age >= 18:
    print('Eligible for voting')
else:
    print('Not eligible for voting')

Enter the age 45


Eligible for voting


## 6 marks

In [52]:
marks = int(input('Enter the marks:'))
if marks > 90:
    print('Grade: A')
elif marks > 75 and marks < 89:
    print('Grade: B')
elif marks > 50 and marks < 74:
    print('Grade: C')
else:
    print('Fail')

Enter the marks: 80


Grade: B


##  7 positive or negative

In [6]:
num = int(input('Enter the number:'))

if num > 0:
    if num % 2 == 0:
        print('positive and even')
    else:
        print('positive and odd')
elif num == 0:
    print('its zero')
else:
    print('its negative')

Enter the number: -45


its negative


## 8

In [7]:
import numpy as np

In [8]:
ad = np.array(5)
ad

array(5)

In [9]:
ad= np.array([1,2,3,4,5])
ad

array([1, 2, 3, 4, 5])

In [17]:
af = np.arange(10, 70, 10).reshape(2, 3)
af

array([[10, 20, 30],
       [40, 50, 60]])

## 9

In [24]:
ag = np.random.randint(0, 100, (4,4))
ag

array([[20, 33, 47, 63],
       [10, 74,  2, 35],
       [96, 64, 91, 95],
       [19, 98, 52, 80]], dtype=int32)

## 10

In [1]:
import numpy as np
import pandas as pd

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])

In [2]:
df

,A,B,C
0,1,2,3
1,4,5,6
2,7,8,9


## 11

In [3]:
import pandas as pd

data = {
    'Name': ['ravi', 'shankar ', 'manoj', 'preetam', 'sachin', 'rakshita', 'laxmi', 'kiran', 'sudeep', 'pavn'],
    'Age': [25, 30, 22, 35, 23, 40, 32, 26, 29, 33],
    'City': ['bgm', 'bng', 'CHI', 'HOU', 'PHX', 'NY', 'LA', 'CHI', 'HOU', 'PHX'],
    'Salary': [50000, None,45000, 70000, 55000, 80000,None
               , 48000, 52000, 62000]
}

df = pd.DataFrame(data)

In [4]:
df

,Name,Age,City,Salary
0,ravi,25,bgm,50000.0
1,shankar,30,bng,NaN
2,manoj,22,CHI,45000.0
3,preetam,35,HOU,70000.0
4,sachin,23,PHX,55000.0
5,rakshita,40,NY,80000.0
6,laxmi,32,LA,NaN
7,kiran,26,CHI,48000.0
8,sudeep,29,HOU,52000.0
9,pavn,33,PHX,62000.0


In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    10 non-null     object
 1   Age     10 non-null     int64 
 2   City    10 non-null     object
 3   Salary  10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes


In [35]:
df.describe()

,Age,Salary
count,10.000000,10.000000
mean,30.000000,58700.000000
std,5.249339,10904.127659
min,22.000000,45000.000000
25%,26.500000,50500.000000
50%,29.500000,57500.000000
75%,32.750000,64250.000000
max,40.000000,80000.000000


In [37]:
df[['Name','City']]

,Name,City
0,ravi,bgm
1,shankar,bng
2,manoj,CHI
3,preetam,HOU
4,sachin,PHX
5,rakshita,NY
6,laxmi,LA
7,kiran,CHI
8,sudeep,HOU
9,pavn,PHX


In [5]:
df.drop(['City'],axis=1)

,Name,Age,Salary
0,ravi,25,50000.0
1,shankar,30,NaN
2,manoj,22,45000.0
3,preetam,35,70000.0
4,sachin,23,55000.0
5,rakshita,40,80000.0
6,laxmi,32,NaN
7,kiran,26,48000.0
8,sudeep,29,52000.0
9,pavn,33,62000.0


In [6]:
df.isnull().count()

Name      10
Age       10
City      10
Salary    10
dtype: int64

In [8]:
ad=df['Salary'].mean()
ad

np.float64(57750.0)

In [9]:
df['Salary'] = df['Salary'].fillna(ad)  ## filling the nan with mean


In [21]:
df

,Name,Age,City,Salary
0,ravi,25,bgm,50000.0
1,shankar,30,bng,46200.0
2,manoj,22,CHI,45000.0
3,preetam,35,HOU,70000.0
4,sachin,23,PHX,55000.0
5,rakshita,40,NY,80000.0
6,laxmi,32,LA,46200.0
7,kiran,26,CHI,48000.0
8,sudeep,29,HOU,52000.0
9,pavn,33,PHX,62000.0
